# example netlify.toml
[build]
  command = "yarn build"
  functions = "src/netlify/functions"
  publish = "dist"

  [dev]
   command = "yarn dev" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
   publish = "dist" # Folder with the static content for _redirect file
   functions = "src/netlify/functions"
   autoLaunch = false

  [[redirects]]
    from = '/api/*'
    to = '/.netlify/functions/api/:splat'
    status = 200

  [functions]
    external_node_modules = ["express", "vm2"]
    node_bundler = 'esbuild'
